version: "3.9"

services:
  fastapi:
    build:
      context: ./src/api
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - app_net

  streamlit:
    build:
      context: ./src/api
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
